sudo: required
language: c++
dist: trusty

cache:
  apt: true
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.9.0

matrix:
  include:
    - os: linux
      env: COMPILER=g++-6 BOOST_VERSION=default
      compiler: gcc

addons:
  apt:
    sources: &sources
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data

before_install:
  - sudo apt-get install verilator
  - sudo apt-get install libboost-dev
  - sudo apt-get install libboost-program-options-dev

script:
  - |
    git submodule init
    git submodule update
    mkdir build
    pushd build
    cmake ../
    make

# TODO: notifications
